Support for dmn model imports
camunda/dmn-scala pull request #215
Opened 2023-04-25 20:31 UTC by tracyhires

## Description

Imported DMN models can be loaded via URI reference, or by namespace if already loaded. This does not fully address issue #71, as a model cannot be loaded from Zeebe

## Related issues

https://github.com/camunda/dmn-scala/issues/71

closes #

2023-04-25 20:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/camunda/dmn-scala?pullRequest=215) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/camunda/dmn-scala?pullRequest=215) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: tracyhires<br/>:x: actions-user<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/camunda/dmn-scala?pullRequest=215) it.</sub>

2023-06-27 06:49 UTC, saig0 requested changes
@tracy-hires I finally reviewed your changes. You found a nice and simple solution to support the importing of DMN files. :tada: 

I have a few minor comments about the changes. But a major concern about the general idea of processing the imported DMN files during the parsing.

On one side, it fits nicely with the current parsing and evaluation logic. But it has some downsides:
- The imported DMNs must be parsed first. So, the order of parsing the DMNs is important. This is a hard requirement, for example, when integrating this into Zeebe. As a user, I (or the process application) deploy all DMNs at once.
- The imported DMNs can't be updated. They are parsed directly into the importing DMN. As a user, I can't deploy only the imported DMNs but I must deploy also the importing DMN. 

To get rid of the downsides, I would suggest processing the imports during the evaluation. I drafted a PoC here #222. 

What do you think? Do you agree with my concern?

2023-06-27 16:27 UTC, tracyhires commented
Your solution to the problem is more elegant than mine, making obsolete both the need to extend the `DmnModelInstanceImpl`, and the accompanying implicit class which was used to overcome the associated issues.

It seems, then, that we should close this PR, and finish the work you've outlined that is yet to be done on https://github.com/camunda/dmn-scala/pull/222. Would you like help completing those items?

2023-07-03 09:22 UTC, saig0 commented
I'm closing this PR in favor of https://github.com/camunda/dmn-scala/pull/222.

---

@tracyhires this topic doesn't have the highest priority for me. But I'll work on it eventually (maybe in Q4 2023). Feel free to contribute based on https://github.com/camunda/dmn-scala/pull/222. :rocket:

2023-10-06 11:54 UTC, closed without merging